max_width = 100
array_width = 100
chain_width = 100
reorder_impl_items = true
use_small_heuristics = "Max"
format_macro_matchers = true
inline_attribute_width = 100
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
condense_wildcard_suffixes = true
comment_width = 100
wrap_comments = true
normalize_comments = true
